### numpy 실습

In [ ]:
import numpy as np

In [ ]:
# 실습 1.
x = [1,2,3,4,5,6,7,8,9]
y = [10,20,30,40,50,60,70,80,90]

In [6]:
x = np.array(x)
y = np.array(y)
x = x.reshape(3,3)
y = y.reshape(3,3)
x, y

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]))

In [9]:
# 행렬합
x + y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [7]:
# 행렬곱
x.dot(y)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [9]:
# 실습 2. 
x = np.linspace(1,20,30)
x + 10

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

In [10]:
# 실습 3.
x = np.random.randint(1, 101, size = (2,10,10))
x

array([[[  2,  61,  59,  14,  91,  13,  65,  72,   2,  22],
        [ 48,  75,  73,  17,  98,  31,   5,  19,  52,  79],
        [ 17,  18,  72,  33,  86,  78,  26,  67, 100,   2],
        [ 48,  80,  50,  61,  68,  11,  84,  36,   6,  69],
        [ 23,  58,  29,   4,  18,  77,  48,  95,  92,  53],
        [ 97,  80,  36,  90,  50,  18,  51,  32,   4,  29],
        [ 24,  51,  16,  95,  26,  63,  30,  21,  79,  89],
        [ 66,  44,  23,  14,  80,  95,  42,  71,   8,  66],
        [ 42,   3,  22,  39,  33,  22,  31,  40,  25,  84],
        [ 44,  68,  96,  83,  44,  19,  86,  74,  70,  56]],

       [[ 51,   9,  65,  26,  37,  74,  33,  85,  31,  95],
        [ 94,  77,  11,  29,  41,  20,  60,  10,  45,  87],
        [ 50,  11,  42,  15,  94,  65,  47,  40,  98,   8],
        [ 17,  39,  54,  88,  31,  87,  62,  43,  81,   7],
        [  3,  94,  72,  32,  60,  68,  36,  41,  52,  36],
        [ 11,   7,  49,  57,  33,   7,  69,  18,  48,  36],
        [ 41,  58,   5,  76,  85,  13,

In [11]:
x = np.where(x >= 50, 1, 2)
x

array([[[2, 1, 1, 2, 1, 2, 1, 1, 2, 2],
        [2, 1, 1, 2, 1, 2, 2, 2, 1, 1],
        [2, 2, 1, 2, 1, 1, 2, 1, 1, 2],
        [2, 1, 1, 1, 1, 2, 1, 2, 2, 1],
        [2, 1, 2, 2, 2, 1, 2, 1, 1, 1],
        [1, 1, 2, 1, 1, 2, 1, 2, 2, 2],
        [2, 1, 2, 1, 2, 1, 2, 2, 1, 1],
        [1, 2, 2, 2, 1, 1, 2, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 1],
        [2, 1, 1, 1, 2, 2, 1, 1, 1, 1]],

       [[1, 2, 1, 2, 2, 1, 2, 1, 2, 1],
        [1, 1, 2, 2, 2, 2, 1, 2, 2, 1],
        [1, 2, 2, 2, 1, 1, 2, 2, 1, 2],
        [2, 2, 1, 1, 2, 1, 1, 2, 1, 2],
        [2, 1, 1, 2, 1, 1, 2, 2, 1, 2],
        [2, 2, 2, 1, 2, 2, 1, 2, 2, 2],
        [2, 1, 2, 1, 1, 2, 1, 2, 2, 1],
        [2, 1, 2, 1, 1, 2, 1, 2, 1, 2],
        [1, 1, 1, 1, 2, 1, 2, 1, 2, 2],
        [2, 2, 1, 1, 2, 2, 2, 1, 2, 2]]])

In [13]:
x[1, 5:10,5:10]

array([[2, 1, 2, 2, 2],
       [2, 1, 2, 2, 1],
       [2, 1, 2, 1, 2],
       [1, 2, 1, 2, 2],
       [2, 2, 1, 2, 2]])

### pandas 실습

In [1]:
import numpy as np
import pandas as pd

In [19]:
# 실습 1
# 1. 결측값 개수 구하기
# 2. 결측값 제거한 series 만들기
# 3. 결측값에 y의 평균값을 넣은 series만들기 

x = [np.nan,1,2,3,4,5]
y = pd.Series([x[np.random.randint(0,6)] for i in range(20)])
y

0     2.0
1     NaN
2     5.0
3     2.0
4     4.0
5     4.0
6     3.0
7     4.0
8     2.0
9     NaN
10    4.0
11    5.0
12    5.0
13    4.0
14    4.0
15    1.0
16    2.0
17    1.0
18    2.0
19    2.0
dtype: float64

In [20]:
y.isnull().sum()

np.int64(2)

In [21]:
no_y = y.dropna()
no_y

0     2.0
2     5.0
3     2.0
4     4.0
5     4.0
6     3.0
7     4.0
8     2.0
10    4.0
11    5.0
12    5.0
13    4.0
14    4.0
15    1.0
16    2.0
17    1.0
18    2.0
19    2.0
dtype: float64

In [22]:
mean_y = y.fillna(y.mean())
mean_y

0     2.000000
1     3.111111
2     5.000000
3     2.000000
4     4.000000
5     4.000000
6     3.000000
7     4.000000
8     2.000000
9     3.111111
10    4.000000
11    5.000000
12    5.000000
13    4.000000
14    4.000000
15    1.000000
16    2.000000
17    1.000000
18    2.000000
19    2.000000
dtype: float64

In [13]:
# 실습 2
# 데이터프레임 만들기 
df = pd.DataFrame(np.random.randint(1, 100, size=(15, 3)),
index = [['1학년','1학년','1학년','1학년','1학년','2학년','2학년','2학년','2학년','2학년','3학년','3학년','3학년','3학년','3학년'],['1반','2반','3반','4반','5반']],
columns=[['국어','영어','과학']])
df

ValueError: all arrays must be same length