### numpy 실습

In [1]:
import numpy as np

In [ ]:
# 실습 1.
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
y = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [ ]:
x = np.array(x)
y = np.array(y)
x = x.reshape(3, 3)
y = y.reshape(3, 3)
x, y

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]))

In [9]:
# 행렬합
x + y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [7]:
# 행렬곱
x.dot(y)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [ ]:
# 실습 2.
x = np.linspace(1, 20, 30)
x + 10

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

In [ ]:
# 실습 3.
# np.int(np.random.rand(2,10,10) * 100 + 1)
x = np.random.randint(1, 101, size=(2, 10, 10))
x

array([[[  2,  61,  59,  14,  91,  13,  65,  72,   2,  22],
        [ 48,  75,  73,  17,  98,  31,   5,  19,  52,  79],
        [ 17,  18,  72,  33,  86,  78,  26,  67, 100,   2],
        [ 48,  80,  50,  61,  68,  11,  84,  36,   6,  69],
        [ 23,  58,  29,   4,  18,  77,  48,  95,  92,  53],
        [ 97,  80,  36,  90,  50,  18,  51,  32,   4,  29],
        [ 24,  51,  16,  95,  26,  63,  30,  21,  79,  89],
        [ 66,  44,  23,  14,  80,  95,  42,  71,   8,  66],
        [ 42,   3,  22,  39,  33,  22,  31,  40,  25,  84],
        [ 44,  68,  96,  83,  44,  19,  86,  74,  70,  56]],

       [[ 51,   9,  65,  26,  37,  74,  33,  85,  31,  95],
        [ 94,  77,  11,  29,  41,  20,  60,  10,  45,  87],
        [ 50,  11,  42,  15,  94,  65,  47,  40,  98,   8],
        [ 17,  39,  54,  88,  31,  87,  62,  43,  81,   7],
        [  3,  94,  72,  32,  60,  68,  36,  41,  52,  36],
        [ 11,   7,  49,  57,  33,   7,  69,  18,  48,  36],
        [ 41,  58,   5,  76,  85,  13,

In [11]:
x = np.where(x >= 50, 1, 2)
x

array([[[2, 1, 1, 2, 1, 2, 1, 1, 2, 2],
        [2, 1, 1, 2, 1, 2, 2, 2, 1, 1],
        [2, 2, 1, 2, 1, 1, 2, 1, 1, 2],
        [2, 1, 1, 1, 1, 2, 1, 2, 2, 1],
        [2, 1, 2, 2, 2, 1, 2, 1, 1, 1],
        [1, 1, 2, 1, 1, 2, 1, 2, 2, 2],
        [2, 1, 2, 1, 2, 1, 2, 2, 1, 1],
        [1, 2, 2, 2, 1, 1, 2, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 1],
        [2, 1, 1, 1, 2, 2, 1, 1, 1, 1]],

       [[1, 2, 1, 2, 2, 1, 2, 1, 2, 1],
        [1, 1, 2, 2, 2, 2, 1, 2, 2, 1],
        [1, 2, 2, 2, 1, 1, 2, 2, 1, 2],
        [2, 2, 1, 1, 2, 1, 1, 2, 1, 2],
        [2, 1, 1, 2, 1, 1, 2, 2, 1, 2],
        [2, 2, 2, 1, 2, 2, 1, 2, 2, 2],
        [2, 1, 2, 1, 1, 2, 1, 2, 2, 1],
        [2, 1, 2, 1, 1, 2, 1, 2, 1, 2],
        [1, 1, 1, 1, 2, 1, 2, 1, 2, 2],
        [2, 2, 1, 1, 2, 2, 2, 1, 2, 2]]])

In [ ]:
x[1, 5:10, 5:10]
# x[1:, -5:, -5:]

array([[2, 1, 2, 2, 2],
       [2, 1, 2, 2, 1],
       [2, 1, 2, 1, 2],
       [1, 2, 1, 2, 2],
       [2, 2, 1, 2, 2]])

### pandas 실습

In [2]:
import numpy as np
import pandas as pd

In [ ]:
# 실습 1
# 1. 결측값 개수 구하기
# 2. 결측값 제거한 series 만들기
# 3. 결측값에 y의 평균값을 넣은 series만들기

x = [np.nan, 1, 2, 3, 4, 5]
y = pd.Series([x[np.random.randint(0, 6)] for i in range(20)])
y

0     2.0
1     NaN
2     5.0
3     2.0
4     4.0
5     4.0
6     3.0
7     4.0
8     2.0
9     NaN
10    4.0
11    5.0
12    5.0
13    4.0
14    4.0
15    1.0
16    2.0
17    1.0
18    2.0
19    2.0
dtype: float64

In [20]:
y.isnull().sum()

np.int64(2)

In [21]:
no_y = y.dropna()
no_y

0     2.0
2     5.0
3     2.0
4     4.0
5     4.0
6     3.0
7     4.0
8     2.0
10    4.0
11    5.0
12    5.0
13    4.0
14    4.0
15    1.0
16    2.0
17    1.0
18    2.0
19    2.0
dtype: float64

In [22]:
mean_y = y.fillna(y.mean())
mean_y

0     2.000000
1     3.111111
2     5.000000
3     2.000000
4     4.000000
5     4.000000
6     3.000000
7     4.000000
8     2.000000
9     3.111111
10    4.000000
11    5.000000
12    5.000000
13    4.000000
14    4.000000
15    1.000000
16    2.000000
17    1.000000
18    2.000000
19    2.000000
dtype: float64

In [ ]:
# 실습 2
# 데이터프레임 만들기
grades = ["1학년"] * 5 + ["2학년"] * 5 + ["3학년"] * 5
# grades = [f'{i}학년' for i in range(1,4) for _ in range(5)]

classes = ["1반", "2반", "3반", "4반", "5반"] * 3
# classes = [f'{i}반' for i in range(1,6)] * 3

df = pd.DataFrame(
    np.random.randint(1, 101, size=(15, 3)),
    index=[grades, classes],
    columns=[["국어", "영어", "과학"]],
)
df

국어  영어  과학
1학년 1반  65  46  39
    2반  60  78  61
    3반  76  55  38
    4반  20  84  70
    5반  84  22  80
2학년 1반  34  38   8
    2반  63  90  38
    3반  73  66  34
    4반  52  39  36
    5반  85  54  56
3학년 1반  25  28  40
    2반  59  44  83
    3반  35  20  83
    4반  97  80  40
    5반  87  73  78

In [ ]:
# 총점 평균 추가

df["총점"] = df.sum(axis=1)
df["평균"] = df["총점"] / 3
df

국어  영어  과학   총점         평균
1학년 1반  68  88  60  216  72.000000
    2반  13   9  13   35  11.666667
    3반  44  78  70  192  64.000000
    4반  13  11  85  109  36.333333
    5반  47   2  72  121  40.333333
2학년 1반  28  20  29   77  25.666667
    2반  57  15  45  117  39.000000
    3반  83  21  34  138  46.000000
    4반  32  25  60  117  39.000000
    5반  15   8  67   90  30.000000
3학년 1반  29  83  64  176  58.666667
    2반  25  35  57  117  39.000000
    3반  51  90  76  217  72.333333
    4반  30  25  39   94  31.333333
    5반  24  28  21   73  24.333333

In [ ]:
# 학년별 합계

df.index.names = ["학년", "반"]
result = df.groupby("학년").sum()
# df.groupby("학년").sum()['국어','영어','과학']/5
result

국어   영어   과학   총점          평균
학년                                 
1학년  185  188  300  673  224.333333
2학년  215   89  235  539  179.666667
3학년  159  261  257  677  225.666667

In [8]:
# 실습 3
titanic = pd.read_csv("./train.csv")
titanic.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [9]:
# 1. 결측치 처리
titanic["Age"] = titanic["Age"].fillna(titanic["Age"].mean())
titanic["Cabin"] = titanic["Cabin"].fillna("N")
titanic["Embarked"] = titanic["Embarked"].fillna("N")
titanic.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500     N        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250     N        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500     N        S

In [10]:
# 2. 성별 생존자 합
titanic.groupby("Sex")["Survived"].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

In [11]:
# 3. 클래스별 생존자 합
titanic.groupby("Pclass")["Survived"].sum()

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

In [12]:
def change(age):
    if age < 10:
        return '유아'
    elif age < 70:
        return f'{int(age// 10)}0대'
    else:
        return '노인'
titanic["Age"].apply(change)

0      20대
1      30대
2      20대
3      30대
4      30대
      ... 
886    20대
887    10대
888    20대
889    20대
890    30대
Name: Age, Length: 891, dtype: object

In [13]:
# 4. 나이별 생존자 합
def age_group(age):
    if age < 10:
        return "유아"
    elif age < 20:
        return "10대"
    elif age < 30:
        return "20대"
    elif age < 40:
        return "30대"
    elif age < 50:
        return "40대"
    elif age < 60:
        return "50대"
    elif age < 70:
        return "60대"
    elif age >= 70:
        return "노인"


titanic["Age_Range"] = titanic["Age"].apply(age_group)
titanic.groupby("Age_Range")["Survived"].sum()

Age_Range
10대     41
20대    129
30대     73
40대     34
50대     20
60대      6
노인       1
유아      38
Name: Survived, dtype: int64

In [14]:
titanic.groupby("Age_Range")["Survived"].sum() / titanic.groupby(['Age_Range']).count()['Survived']

Age_Range
10대    0.401961
20대    0.324937
30대    0.437126
40대    0.382022
50대    0.416667
60대    0.315789
노인     0.142857
유아     0.612903
Name: Survived, dtype: float64